// Phase 3B: pure "smart insights" detection (no DB). Finds likely subscriptions in
// spending history and per-category spend anomalies. Kept pure like balance.ts so the
// logic is trivially unit-testable; the service maps DB rows into these shapes.
import { advance, type Cadence } from "./recurring";

export type InsightExpense = {
  _id: string;
  description: string;
  category: string;
  amount: number; // base currency
  date: string; // ISO
  recurringId: string | null;
};

export type DetectedSubscription = {
  key: string;
  description: string;
  category: string;
  cadence: Cadence;
  amount: number; // latest amount (base)
  occurrences: number;
  lastDate: string;
  nextDate: string; // suggested start if the user tracks it
  priceChange: number | null; // latest − previous, when it changed
};

export type Anomaly = {
  _id: string;
  description: string;
  category: string;
  amount: number;
  date: string;
  median: number;
  ratio: number; // amount / category median
};

const DAY = 86400000;
const normalize = (s: string) => s.trim().toLowerCase().replace(/\s+/g, " ");

function median(nums: number[]): number {
  if (nums.length === 0) return 0;
  const s = [...nums].sort((a, b) => a - b);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 ? s[mid] : (s[mid - 1] + s[mid]) / 2;
}

function cadenceFromGap(days: number): Cadence | null {
  if (days >= 5 && days <= 9) return "weekly";
  if (days >= 24 && days <= 35) return "monthly";
  if (days >= 350 && days <= 380) return "yearly";
  return null;
}

const round = (n: number) => Math.round(n * 100) / 100;

/**
 * Detect likely subscriptions: same description appearing on a roughly regular
 * cadence (≥3 times). Skips rows already generated by a recurring rule and any
 * description already tracked (`trackedKeys`). Flags a price change vs the prior charge.
 */
export function detectSubscriptions(
  expenses: InsightExpense[],
  trackedKeys: Set<string> = new Set()
): DetectedSubscription[] {
  const groups = new Map<string, InsightExpense[]>();
  for (const e of expenses) {
    if (e.recurringId) continue; // already a recurring rule's output
    const key = normalize(e.description);
    if (!key || trackedKeys.has(key)) continue;
    (groups.get(key) ?? groups.set(key, []).get(key)!).push(e);
  }

  const out: DetectedSubscription[] = [];
  for (const [key, rows] of groups) {
    if (rows.length < 3) continue;
    rows.sort((a, b) => Date.parse(a.date) - Date.parse(b.date));

    const gaps: number[] = [];
    for (let i = 1; i < rows.length; i++) {
      gaps.push((Date.parse(rows[i].date) - Date.parse(rows[i - 1].date)) / DAY);
    }
    const medGap = median(gaps);
    const cadence = cadenceFromGap(medGap);
    if (!cadence) continue;

    // Regular if every gap is within ±50% of the median gap.
    const regular = gaps.every(
      (g) => g >= medGap * 0.5 && g <= medGap * 1.5
    );
    if (!regular) continue;

    const last = rows[rows.length - 1];
    const prev = rows[rows.length - 2];
    const priceChange =
      Math.abs(last.amount - prev.amount) >= 1 ? round(last.amount - prev.amount) : null;
    const nextDate = advance(new Date(last.date), cadence).toISOString().slice(0, 10);

    out.push({
      key,
      description: last.description,
      category: last.category,
      cadence,
      amount: round(last.amount),
      occurrences: rows.length,
      lastDate: new Date(last.date).toISOString().slice(0, 10),
      nextDate,
      priceChange,
    });
  }
  // Most recent first.
  return out.sort((a, b) => Date.parse(b.lastDate) - Date.parse(a.lastDate));
}

/**
 * Per-category spend anomalies: in categories with enough history, flag charges that
 * are a large multiple of the category's median. `floor` avoids noise from tiny spends.
 */
export function detectAnomalies(
  expenses: InsightExpense[],
  opts: { factor?: number; floor?: number; minSamples?: number; limit?: number } = {}
): Anomaly[] {
  const factor = opts.factor ?? 3;
  const floor = opts.floor ?? 300;
  const minSamples = opts.minSamples ?? 4;
  const limit = opts.limit ?? 5;

  const byCat = new Map<string, InsightExpense[]>();
  for (const e of expenses) {
    (byCat.get(e.category) ?? byCat.set(e.category, []).get(e.category)!).push(e);
  }

  const anomalies: Anomaly[] = [];
  for (const [category, rows] of byCat) {
    if (rows.length < minSamples) continue;
    const med = median(rows.map((r) => r.amount));
    if (med <= 0) continue;
    for (const e of rows) {
      if (e.amount >= floor && e.amount >= factor * med) {
        anomalies.push({
          _id: e._id,
          description: e.description,
          category,
          amount: round(e.amount),
          date: new Date(e.date).toISOString().slice(0, 10),
          median: round(med),
          ratio: round(e.amount / med),
        });
      }
    }
  }
  return anomalies.sort((a, b) => b.ratio - a.ratio).slice(0, limit);
}
