"use client";

import { useState } from "react";
import { useAuth } from "@/lib/authContext";

type CategoryEntry = { category: string; total: number; count: number };
type MonthEntry = { year: number; month: number; total: number; count: number };

type Summary = {
  totalAmount: number;
  totalCount: number;
  byCategory: CategoryEntry[];
  byMonth: MonthEntry[];
};

type Props = {
  summary: Summary;
  dateFrom?: string;
  dateTo?: string;
};

const MONTH_NAMES = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

export function ExportPdfButton({ summary, dateFrom, dateTo }: Props) {
  const { authFetch, user } = useAuth();
  const [exporting, setExporting] = useState(false);

  async function handleExport() {
    setExporting(true);

    try {
      const { default: jsPDF } = await import("jspdf");
      await import("jspdf-autotable");

      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      let y = 20;

      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("Expense Report", pageWidth / 2, y, { align: "center" });
      y += 10;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);
      const range =
        dateFrom || dateTo
          ? `${dateFrom || "Start"} to ${dateTo || "Present"}`
          : "All time";
      doc.text(`Period: ${range}`, pageWidth / 2, y, { align: "center" });
      y += 5;
      doc.text(
        `Generated by ${user?.name ?? "User"} on ${new Date().toLocaleDateString()}`,
        pageWidth / 2,
        y,
        { align: "center" }
      );
      y += 12;

      doc.setTextColor(0);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Summary", 14, y);
      y += 8;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`Total Expenses: Rs.${summary.totalAmount.toFixed(2)}`, 14, y);
      y += 6;
      doc.text(`Number of Entries: ${summary.totalCount}`, 14, y);
      y += 12;

      if (summary.byCategory.length > 0) {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("Category Breakdown", 14, y);
        y += 4;

        (doc as any).autoTable({
          startY: y,
          head: [["Category", "Count", "Total (Rs.)", "% of Total"]],
          body: summary.byCategory.map((c) => [
            c.category,
            c.count.toString(),
            `Rs.${c.total.toFixed(2)}`,
            `${((c.total / summary.totalAmount) * 100).toFixed(1)}%`,
          ]),
          styles: { fontSize: 9, cellPadding: 3 },
          headStyles: { fillColor: [99, 102, 241] },
          alternateRowStyles: { fillColor: [245, 245, 250] },
        });

        y = (doc as any).lastAutoTable.finalY + 12;
      }

      if (summary.byMonth.length > 0) {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("Monthly Trend", 14, y);
        y += 4;

        (doc as any).autoTable({
          startY: y,
          head: [["Month", "Count", "Total (Rs.)"]],
          body: summary.byMonth.map((m) => [
            `${MONTH_NAMES[m.month - 1]} ${m.year}`,
            m.count.toString(),
            `Rs.${m.total.toFixed(2)}`,
          ]),
          styles: { fontSize: 9, cellPadding: 3 },
          headStyles: { fillColor: [99, 102, 241] },
          alternateRowStyles: { fillColor: [245, 245, 250] },
        });

        y = (doc as any).lastAutoTable.finalY + 12;
      }

      // Fetch expenses for the full list
      const params = new URLSearchParams({ limit: "200" });
      if (dateFrom) params.set("dateFrom", dateFrom);
      if (dateTo) params.set("dateTo", dateTo);
      const expRes = await authFetch(
        `/api/projects/expense-tracker/expenses?${params}`
      );
      const expData = await expRes.json();
      const expenses = expData.expenses ?? [];

      if (expenses.length > 0) {
        if (y > 240) {
          doc.addPage();
          y = 20;
        }
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("All Expenses", 14, y);
        y += 4;

        (doc as any).autoTable({
          startY: y,
          head: [["Date", "Description", "Category", "Paid By", "Amount (Rs.)", "Type"]],
          body: expenses.map((e: any) => [
            new Date(e.date).toLocaleDateString(),
            e.description,
            e.category,
            e.paidBy?.name ?? "-",
            `Rs.${e.amount.toFixed(2)}`,
            e.type,
          ]),
          styles: { fontSize: 8, cellPadding: 2 },
          headStyles: { fillColor: [99, 102, 241] },
          alternateRowStyles: { fillColor: [245, 245, 250] },
          columnStyles: {
            4: { halign: "right" },
          },
        });

        y = (doc as any).lastAutoTable.finalY + 12;
      }

      // Fetch group settlements
      const groupsRes = await authFetch("/api/projects/expense-tracker/groups");
      const groupsData = await groupsRes.json();
      const groups = groupsData.groups ?? [];

      for (const group of groups) {
        const balRes = await authFetch(
          `/api/projects/expense-tracker/reports/balances/${group._id}`
        );
        const balData = await balRes.json();
        const { balances, settlements } = balData;

        if (settlements && settlements.length > 0) {
          if (y > 240) {
            doc.addPage();
            y = 20;
          }

          doc.setFontSize(12);
          doc.setFont("helvetica", "bold");
          doc.text(`Settlements — ${group.name}`, 14, y);
          y += 4;

          if (balances && balances.length > 0) {
            (doc as any).autoTable({
              startY: y,
              head: [["Member", "Paid", "Owes", "Net Balance"]],
              body: balances.map((b: any) => [
                b.name,
                `Rs.${b.totalPaid.toFixed(2)}`,
                `Rs.${b.totalOwed.toFixed(2)}`,
                `${b.netBalance > 0 ? "+" : ""}Rs.${b.netBalance.toFixed(2)}`,
              ]),
              styles: { fontSize: 9, cellPadding: 3 },
              headStyles: { fillColor: [99, 102, 241] },
              alternateRowStyles: { fillColor: [245, 245, 250] },
            });
            y = (doc as any).lastAutoTable.finalY + 6;
          }

          (doc as any).autoTable({
            startY: y,
            head: [["From", "To", "Amount (Rs.)"]],
            body: settlements.map((s: any) => [
              s.from.name,
              s.to.name,
              `Rs.${s.amount.toFixed(2)}`,
            ]),
            styles: { fontSize: 9, cellPadding: 3 },
            headStyles: { fillColor: [245, 158, 11] },
            alternateRowStyles: { fillColor: [255, 251, 235] },
          });

          y = (doc as any).lastAutoTable.finalY + 12;
        }
      }

      const fileName = `expense-report-${new Date().toISOString().slice(0, 10)}.pdf`;
      doc.save(fileName);
    } catch (err) {
      console.error("PDF export failed:", err);
      alert("Failed to export PDF. Check console for details.");
    } finally {
      setExporting(false);
    }
  }

  return (
    <button
      onClick={handleExport}
      disabled={exporting}
      className="rounded-lg border border-brand-500 px-4 py-2 text-xs font-medium text-brand-500 transition hover:bg-brand-500/10 disabled:opacity-50"
    >
      {exporting ? "Generating PDF..." : "Export PDF"}
    </button>
  );
}
