"use client";

import { useState } from "react";
import { useAuth } from "@/lib/authContext";

type CategoryEntry = { category: string; total: number; count: number };
type MonthEntry = { year: number; month: number; total: number; count: number };

type Summary = {
  totalAmount: number;
  totalCount: number;
  byCategory: CategoryEntry[];
  byMonth: MonthEntry[];
};

type Props = {
  summary: Summary;
  dateFrom?: string;
  dateTo?: string;
};

const MONTH_NAMES = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

export function ExportPdfButton({ summary, dateFrom, dateTo }: Props) {
  const { authFetch, user } = useAuth();
  const [exporting, setExporting] = useState(false);

  async function handleExport() {
    setExporting(true);

    try {
      const { default: jsPDF } = await import("jspdf");
      await import("jspdf-autotable");

      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      let y = 20;

      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("Expense Report", pageWidth / 2, y, { align: "center" });
      y += 10;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);
      const range =
        dateFrom || dateTo
          ? `${dateFrom || "Start"} to ${dateTo || "Present"}`
          : "All time";
      doc.text(`Period: ${range}`, pageWidth / 2, y, { align: "center" });
      y += 5;
      doc.text(
        `Generated by ${user?.name ?? "User"} on ${new Date().toLocaleDateString()}`,
        pageWidth / 2,
        y,
        { align: "center" }
      );
      y += 12;

      doc.setTextColor(0);
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Summary", 14, y);
      y += 8;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`Total Expenses: Rs.${summary.totalAmount.toFixed(2)}`, 14, y);
      y += 6;
      doc.text(`Number of Entries: ${summary.totalCount}`, 14, y);
      y += 12;

      if (summary.byCategory.length > 0) {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("Category Breakdown", 14, y);
        y += 4;

        (doc as any).autoTable({
          startY: y,
          head: [["Category", "Count", "Total (Rs.)", "% of Total"]],
          body: summary.byCategory.map((c) => [
            c.category,
            c.count.toString(),
            `Rs.${c.total.toFixed(2)}`,
            `${((c.total / summary.totalAmount) * 100).toFixed(1)}%`,
          ]),
          styles: { fontSize: 9, cellPadding: 3 },
          headStyles: { fillColor: [99, 102, 241] },
          alternateRowStyles: { fillColor: [245, 245, 250] },
        });

        y = (doc as any).lastAutoTable.finalY + 12;
      }

      if (summary.byMonth.length > 0) {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("Monthly Trend", 14, y);
        y += 4;

        (doc as any).autoTable({
          startY: y,
          head: [["Month", "Count", "Total (Rs.)"]],
          body: summary.byMonth.map((m) => [
            `${MONTH_NAMES[m.month - 1]} ${m.year}`,
            m.count.toString(),
            `Rs.${m.total.toFixed(2)}`,
          ]),
          styles: { fontSize: 9, cellPadding: 3 },
          headStyles: { fillColor: [99, 102, 241] },
          alternateRowStyles: { fillColor: [245, 245, 250] },
        });

        y = (doc as any).lastAutoTable.finalY + 12;
      }

      // Fetch expenses for the full list (include all settled + unsettled)
      const params = new URLSearchParams({ limit: "200", settled: "all" });
      if (dateFrom) params.set("dateFrom", dateFrom);
      if (dateTo) params.set("dateTo", dateTo);
      const expRes = await authFetch(
        `/api/projects/expense-tracker/expenses?${params}`
      );
      const expData = await expRes.json();
      console.log("[pdf] expenses fetched:", expData.total ?? 0);
      const expenses = expData.expenses ?? [];

      if (expenses.length > 0) {
        if (y > 240) {
          doc.addPage();
          y = 20;
        }
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("All Expenses", 14, y);
        y += 4;

        (doc as any).autoTable({
          startY: y,
          head: [["Date", "Description", "Category", "Paid By", "Split Among", "Amount (Rs.)", "Type"]],
          body: expenses.map((e: any) => [
            new Date(e.date).toLocaleDateString(),
            e.description,
            e.category,
            e.paidBy?.name ?? "-",
            e.splitAmong?.length > 0
              ? e.splitAmong.map((m: any) => m.name).join(", ")
              : "-",
            `Rs.${e.amount.toFixed(2)}`,
            e.type,
          ]),
          styles: { fontSize: 7, cellPadding: 2 },
          headStyles: { fillColor: [99, 102, 241] },
          alternateRowStyles: { fillColor: [245, 245, 250] },
          columnStyles: {
            5: { halign: "right" },
          },
        });

        y = (doc as any).lastAutoTable.finalY + 12;
      }

      // Fetch group details with settlements
      const groupsRes = await authFetch("/api/projects/expense-tracker/groups");
      const groupsData = await groupsRes.json();
      const groups = groupsData.groups ?? [];
      console.log("[pdf] groups fetched:", groups.length, groups.map((g: any) => g.name));

      for (const group of groups) {
        let balData: any = { balances: [], settlements: [] };
        let grpExpData: any = { expenses: [] };

        try {
          const [balRes, grpExpRes] = await Promise.all([
            authFetch(`/api/projects/expense-tracker/reports/balances/${group._id}`),
            authFetch(`/api/projects/expense-tracker/expenses?groupId=${group._id}&limit=200&settled=all`),
          ]);
          balData = await balRes.json();
          grpExpData = await grpExpRes.json();
        } catch (err) {
          console.error("[pdf] failed to fetch group data for", group.name, err);
        }

        console.log("[pdf] group", group.name, "expenses:", grpExpData.expenses?.length ?? 0);

        const { balances, settlements } = balData;
        const groupExpenses = grpExpData.expenses ?? [];

        if (groupExpenses.length === 0) continue;

        if (y > 220) {
          doc.addPage();
          y = 20;
        }

        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text(`Group: ${group.name}`, 14, y);
        y += 4;

        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100);
        doc.text(
          `Members: ${group.members.map((m: any) => m.name).join(", ")}`,
          14,
          y + 4
        );
        doc.setTextColor(0);
        y += 12;

        // Per-member spending summary
        const memberSpend = new Map<string, { name: string; paid: number; owes: number }>();
        for (const e of groupExpenses) {
          const payerId = e.paidBy?.id ?? e.paidBy?.name;
          const payerName = e.paidBy?.name ?? "-";
          if (!memberSpend.has(payerId)) {
            memberSpend.set(payerId, { name: payerName, paid: 0, owes: 0 });
          }
          memberSpend.get(payerId)!.paid += e.amount;

          for (const s of e.splits ?? []) {
            if (!memberSpend.has(s.memberId)) {
              memberSpend.set(s.memberId, { name: s.name, paid: 0, owes: 0 });
            }
            memberSpend.get(s.memberId)!.owes += s.amount;
          }
        }

        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text("Member Spending Summary", 14, y);
        y += 4;

        (doc as any).autoTable({
          startY: y,
          head: [["Member", "Total Paid", "Total Share", "Net"]],
          body: Array.from(memberSpend.values()).map((m) => {
            const net = m.paid - m.owes;
            return [
              m.name,
              `Rs.${m.paid.toFixed(2)}`,
              `Rs.${m.owes.toFixed(2)}`,
              `${net > 0 ? "+" : ""}Rs.${net.toFixed(2)}`,
            ];
          }),
          styles: { fontSize: 9, cellPadding: 3 },
          headStyles: { fillColor: [99, 102, 241] },
          alternateRowStyles: { fillColor: [245, 245, 250] },
        });
        y = (doc as any).lastAutoTable.finalY + 8;

        // Settlement plan
        if (settlements && settlements.length > 0) {
          if (y > 250) {
            doc.addPage();
            y = 20;
          }

          doc.setFontSize(11);
          doc.setFont("helvetica", "bold");
          doc.text("Settlement Plan", 14, y);
          y += 4;

          (doc as any).autoTable({
            startY: y,
            head: [["From", "Pays To", "Amount (Rs.)"]],
            body: settlements.map((s: any) => [
              s.from.name,
              s.to.name,
              `Rs.${s.amount.toFixed(2)}`,
            ]),
            styles: { fontSize: 9, cellPadding: 3 },
            headStyles: { fillColor: [245, 158, 11] },
            alternateRowStyles: { fillColor: [255, 251, 235] },
          });
          y = (doc as any).lastAutoTable.finalY + 8;
        } else if (balances && balances.length > 0) {
          doc.setFontSize(9);
          doc.setFont("helvetica", "italic");
          doc.setTextColor(34, 197, 94);
          doc.text("All settled — no pending payments.", 14, y);
          doc.setTextColor(0);
          y += 8;
        }

        // Group expenses detail
        if (y > 240) {
          doc.addPage();
          y = 20;
        }

        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text(`Expense Details (${groupExpenses.length} entries)`, 14, y);
        y += 4;

        (doc as any).autoTable({
          startY: y,
          head: [["Date", "Description", "Paid By", "Split Among", "Amount (Rs.)"]],
          body: groupExpenses.map((e: any) => [
            new Date(e.date).toLocaleDateString(),
            e.description,
            e.paidBy?.name ?? "-",
            e.splitAmong?.map((m: any) => m.name).join(", ") ?? "-",
            `Rs.${e.amount.toFixed(2)}`,
          ]),
          styles: { fontSize: 8, cellPadding: 2 },
          headStyles: { fillColor: [99, 102, 241] },
          alternateRowStyles: { fillColor: [245, 245, 250] },
          columnStyles: {
            4: { halign: "right" },
          },
        });

        y = (doc as any).lastAutoTable.finalY + 14;
      }

      const fileName = `expense-report-${new Date().toISOString().slice(0, 10)}.pdf`;
      doc.save(fileName);
    } catch (err) {
      console.error("PDF export failed:", err);
      alert("Failed to export PDF. Check console for details.");
    } finally {
      setExporting(false);
    }
  }

  return (
    <button
      onClick={handleExport}
      disabled={exporting}
      className="rounded-lg border border-brand-500 px-4 py-2 text-xs font-medium text-brand-500 transition hover:bg-brand-500/10 disabled:opacity-50"
    >
      {exporting ? "Generating PDF..." : "Export PDF"}
    </button>
  );
}
