import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import type { Summary } from "./types";

const MONTHS = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

const rs = (n: number) => `Rs.${n.toFixed(2)}`;
const esc = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function row(cells: (string | number)[], right = -1) {
  return `<tr>${cells
    .map(
      (c, i) =>
        `<td style="${i === right ? "text-align:right;" : ""}">${
          typeof c === "string" ? esc(c) : c
        }</td>`
    )
    .join("")}</tr>`;
}

function table(head: string[], rows: string): string {
  return `<table>
    <thead><tr>${head
      .map((h) => `<th>${esc(h)}</th>`)
      .join("")}</tr></thead>
    <tbody>${rows}</tbody>
  </table>`;
}

/**
 * Builds a summary report PDF (stats + top groups + category breakdown +
 * monthly trend) and opens the OS share sheet. Mirrors the web Export PDF,
 * at the summary level.
 */
export async function exportSummaryPdf(opts: {
  summary: Summary;
  userName?: string;
  dateFrom?: string;
  dateTo?: string;
  title?: string;
}) {
  const { summary, userName, dateFrom, dateTo, title = "Expense Report" } = opts;
  const period =
    dateFrom || dateTo
      ? `${dateFrom || "Start"} to ${dateTo || "Present"}`
      : "All time";

  const topGroups =
    summary.byGroup.length > 0
      ? `<h2>Top Groups</h2>` +
        table(
          ["Group", "Entries", "Total", "My Share"],
          summary.byGroup
            .map((g) => row([g.groupName, g.count, rs(g.total), rs(g.myShare)], 3))
            .join("")
        )
      : "";

  const categories =
    summary.byCategory.length > 0
      ? `<h2>Category Breakdown</h2>` +
        table(
          ["Category", "Count", "Total", "% of Total"],
          summary.byCategory
            .map((c) =>
              row(
                [
                  c.category,
                  c.count,
                  rs(c.total),
                  `${((c.total / summary.totalAmount) * 100).toFixed(1)}%`,
                ],
                3
              )
            )
            .join("")
        )
      : "";

  const monthly =
    summary.byMonth.length > 0
      ? `<h2>Monthly Trend</h2>` +
        table(
          ["Month", "Count", "Total"],
          summary.byMonth
            .map((m) =>
              row([`${MONTHS[m.month - 1]} ${m.year}`, m.count, rs(m.total)], 2)
            )
            .join("")
        )
      : "";

  const largest = summary.largest
    ? `<p><b>Largest:</b> ${esc(summary.largest.description)} — ${rs(
        summary.largest.amount
      )} (${new Date(summary.largest.date).toLocaleDateString()})</p>`
    : "";

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1a1a1a; padding: 28px; }
    h1 { text-align: center; margin: 0 0 4px; font-size: 22px; }
    .sub { text-align: center; color: #666; font-size: 12px; margin: 2px 0; }
    h2 { font-size: 14px; margin: 22px 0 8px; color: #4f46e5; }
    .stats { margin-top: 18px; }
    .stats p { margin: 4px 0; font-size: 13px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th { background: #6366f1; color: #fff; text-align: left; padding: 6px 8px; }
    td { padding: 6px 8px; border-bottom: 1px solid #eee; }
    tbody tr:nth-child(even) { background: #f5f5fa; }
  </style></head>
  <body>
    <h1>${esc(title)}</h1>
    <div class="sub">Period: ${esc(period)}</div>
    <div class="sub">Generated by ${esc(userName ?? "User")} on ${new Date().toLocaleDateString()}</div>
    <div class="stats">
      <h2>Summary</h2>
      <p><b>Total Expenses:</b> ${rs(summary.totalAmount)} &nbsp;·&nbsp; <b>Entries:</b> ${summary.totalCount}</p>
      <p><b>My Share:</b> ${rs(summary.myShare)} &nbsp;·&nbsp; <b>Paid by Me:</b> ${rs(summary.paidByMe)} &nbsp;·&nbsp; <b>Paid by Others:</b> ${rs(summary.paidByOthers)}</p>
      <p><b>Avg/Day:</b> ${rs(summary.averagePerDay)} &nbsp;·&nbsp; <b>Avg/Txn:</b> ${rs(summary.averagePerTransaction)} &nbsp;·&nbsp; <b>Days:</b> ${summary.daysCovered}</p>
      ${largest}
    </div>
    ${topGroups}
    ${categories}
    ${monthly}
  </body></html>`;

  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: title,
      UTI: "com.adobe.pdf",
    });
  }
}
